[package]
name = "agent-client"
version = "1.0.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
sysinfo = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1", features = ["v4"] }
dirs = "5"
get_if_addrs = "0.5"
#reqwest = { version = "0.11", features = ["blocking", "json", "native-tls"] }
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
chrono = { version = "0.4", features = ["serde"] }
redis = "0.24"  #
sha2 = "0.10"
md5 = "0.7"





